name: cargo build && cargo test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Cache cargo deps
      uses: actions/cache@v1.2.1
      env:
        cache-name: cache-deps
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        path: |
          target/debug/deps
          ~/.cargo
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
